/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Squarer */

#ifndef _Included_Squarer
#define _Included_Squarer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Squarer
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Squarer_square
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
